Clone functions from a .ll file
ballerina-platform/nballerina-cpp pull request #300
Opened 2021-05-10 04:02 UTC by ushirask

## Purpose
 Keep commonly used LLVM functions in a .ll file and inject them to the module.
Resolves #275 

## Approach
The .ll file containing the functions are parsed as a separate module using _parseLLFile_. _replaceProtoFunc_ clones the function with the given name into the current module from the parsed module and returns the function callee. 
```
std::unique_ptr<llvm::Module> srcMod = CodeGenUtils::parseLLFile(moduleGenerator.getModule().getContext());
auto AddFunc = CodeGenUtils::replaceProtoFunc("addx",moduleGenerator.getModule(), srcMod.get());
```

2021-05-10 09:42 UTC, shubhamnarlawar commented on compiler/codegen/CodeGenUtils.cpp
> +
Empty line here.

2021-05-10 09:42 UTC, shubhamnarlawar commented on compiler/codegen/CodeGenUtils.cpp
> +
Ditto.

2021-05-10 09:43 UTC, ushirask commented
The PR will be changed to call a cloned function to get end-to-end functionality

2021-05-11 11:10 UTC, shubhamnarlawar commented on compiler/codegen/CodeGenUtils.cpp
> +
blank space.

2021-05-14 05:05 UTC, ushirask commented
This PR now calls the "addx" function to get end to end functionality

2021-05-14 07:00 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SmallVector<llvm::ReturnInst*, 8> returns;
For my info, why a vector of len 8?

2021-05-14 07:06 UTC, ruvi-d commented on compiler/codegen/CodeGenerator.cpp
> +
This "inject addx function" logic should be abstracted away in a separate class that accepts a module obj. similar to :
```
    PackageCodeGen generator(mod);
    generator.visit(translatableObj, builder);
```
But more like this:
```
InlinePreGeneratedFunctions::patch(mod);
```

2021-05-14 07:08 UTC, ruvi-d commented
Please clean the commit history

2021-05-14 07:10 UTC, ruvi-d commented
@ushirask please start a separate discussion on the portability aspect of the .ll file path as mentioned here : https://github.com/ballerina-platform/nballerina/pull/300#discussion_r632313899

2021-05-14 07:13 UTC, ruvi-d commented
@ushirask Noticed that you are not inlining the imported functions. Did you not look into it or did you get blocked?

2021-05-14 07:23 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    if (destFunc != NULL){
Will this not be needed in case we have to create a function inside nballerina itself rather than cloning into a function declared in the BIR?

2021-05-14 07:26 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    }
It seems that the Stackoveflow answer is misleading types are not copied correctly when not initialized.

2021-05-14 08:09 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    std::unique_ptr<llvm::Module> srcModule = llvm::parseIRFile(LLFilePath+fileName, Err, mContext);
Started in #307 
Would this be a problem as LLFilePath is taken from config.h where it will be generated as an absolute path?

2021-05-14 08:29 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    }
hmm.. ok
I'd change this to 
```C++
    for (auto srcArgs = srcFunc->arg_begin(), destArgs = destFunc->arg_begin(); srcArgs != srcFunc->arg_end();
         ++destArgs, ++srcArgs) {
        valuemap[srcArgs] = destArgs;
    }
```

2021-05-14 09:14 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SmallVector<llvm::ReturnInst*, 8> returns;
There is no concrete reason other than it's commonly used.

2021-05-14 09:19 UTC, ushirask commented on compiler/codegen/CodeGenerator.cpp
> +        CodeGenUtils::replaceProtoFunc("addx",mod, srcMod.get());
Returned function is not used as it is already called in ballerina. However it will be needed if we are creating the call to the function within nballerina itself.

2021-05-14 09:26 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +        }
In the case if _replaceProtoFunc_ is used multiple times for the same function, we'll need to check if the function is defined or only declared to prevent multiple definitions.

2021-05-14 10:11 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SmallVector<llvm::ReturnInst*, 8> returns;
That's not very convincing :-)
Make the size zero, if there is no effect. We don't need to allocate more space than we need to.

2021-05-14 11:08 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SmallVector<llvm::ReturnInst*, 8> returns;
I used that value as I believe the recommended size is 8 as within LLVM, when function LLVM::CloneFunction calls LLVM::CloneFunctionInto they have used size if 8, I'll try with smaller values and update

2021-05-17 09:51 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SMDiagnostic Err;
changed to std::cerr for printing errors

2021-05-17 09:52 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +    if (destFunc != NULL){
removed NULL check

2021-05-17 09:53 UTC, ushirask commented on compiler/codegen/CodeGenUtils.cpp
> +        }
removed isDeclaration check

2021-05-17 09:55 UTC, ushirask commented
> @ushirask Noticed that you are not inlining the imported functions. Did you not look into it or did you get blocked?

The _addx_ test function is not inlined as it is not called within nballerina. We can inline function calls with 
```
llvm::CallBase* call = mBuilder -> CreateCall( mod0 -> getFunction("addx"), arguments);
llvm::InlineFunctionInfo ifi;
llvm::InlineFunction(*call,ifi);
```

2021-05-17 09:56 UTC, ruvi-d requested changes

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/InlinePregeneratedFunctions.cpp
> +} // namespace nballerina
Missing EoF

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    if (!M) {
replace with `if(srcModule.get() == nullptr){`

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    if (!M) {
isn't `if (!srcModule)` and `if(srcModule.get() == nullptr)` check the same thing?

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::Function *srcFunc = srcModule.getFunction(funcName);
Better add an assert to check `destFunc` and `srcFunc`, so that we can easily catch logic issues in the future.

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    llvm::SMDiagnostic Err;
I suppose you can use `Err` to get additional info is there is an error parsing the file.

2021-05-17 09:56 UTC, ruvi-d commented on compiler/include/codegen/InlinePregeneratedFunctions.h
> +    static void patch(llvm::Module &mod, std::unique_ptr<llvm::Module> &srcMod);
Passing a std::unique_ptr imply a transfer of ownership. Pass a reference or pointer (depending on whether nullptr is a valid value) if that is not the case

2021-05-17 09:56 UTC, ruvi-d commented on compiler/codegen/InlinePregeneratedFunctions.cpp
> +            srcMod = CodeGenUtils::parseLLFile(mod.getContext(), addSrcFile);
Please see the comment about passing a unique pointer. 
Either way, you should probably use `.reset()` here.

2021-05-17 09:56 UTC, ruvi-d commented on compiler/include/codegen/PackageCodeGen.h
> +    std::unique_ptr<llvm::Module> srcMod;
Shouldn't this be in `InlinePregeneratedFunctions` ?

2021-05-17 09:56 UTC, ruvi-d commented on runtime/common/config.h.in
> +#ifndef LL_PATH_CONFIG
If `LL_PATH_CONFIG` is not defined, it should be defined to prevent multiple definitions of `LL_FILE_PATH`. Please check the standard header guard format for C headers.

2021-05-17 10:00 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    std::unique_ptr<llvm::Module> srcModule = llvm::parseIRFile(LLFilePath+fileName, Err, mContext);
This approach is not viable for when we want to distribute compiled binaries to end users

2021-05-17 11:59 UTC, ruvi-d requested changes

2021-05-17 11:59 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
>      if (srcModule.get() == nullptr) {
use the bool operator here: `if (!srcModule)`. [Ref](http://www.cplusplus.com/reference/memory/unique_ptr/operator%20bool/)

2021-05-17 11:59 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    }
Use cassert here. `assert(destFunc!=nullptr);`
It would only be needed for development purposes and should be OK to skip for release builds

2021-05-17 11:59 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +    if (srcFunc==nullptr){
ditto

2021-05-17 11:59 UTC, ruvi-d commented on compiler/codegen/InlinePregeneratedFunctions.cpp
> +        if (srcMod==nullptr) {
ditto about unique_ptr bool operator

2021-05-17 11:59 UTC, ruvi-d commented on runtime/common/config.h.in
> +#endif
```
#ifndef __COMMON_CONFIG__H__
#define __COMMON_CONFIG__H__

#define LL_FILE_PATH "@PROJECT_SOURCE_DIR@/runtime/common/"

#endif //!__COMMON_CONFIG__H__
```

2021-05-17 12:20 UTC, ruvi-d approved these changes

2021-05-19 12:06 UTC, shubhamnarlawar commented on test/inject-ll/addx.bal
> +public function addx(int a, int b) returns int= external;
There should be space between int=
Run - bal format addx.bal

2021-11-05 03:56 UTC, manuranga commented
Closeing since project is moving to attic

2021-11-05 03:56 UTC, closed without merging