Implement array access using the C runtime
ballerina-platform/nballerina-cpp pull request #312
Opened 2021-05-17 07:47 UTC by heshanpadmasiri

## Purpose
Allow array access using the type information in the header

## Goals
Allow array access when one array is casted to another  using the header of the underlying array
Currently support:
 * int -> any
 * byte -> any
 * byte -> int

## Approach
* Change the array store functionality to check for actual array type using the header
* Moved the array load function to the C runtime
* Change the array load function to check for both actual array type and destination type

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
Uses the C runtime from #288
Depend on byte array implementation in #301 

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-05-20 09:45 UTC, ruvi-d requested changes

2021-05-20 09:45 UTC, ruvi-d commented on test/array/cast_int_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Why is this test skipped?

2021-05-20 09:45 UTC, ruvi-d commented on test/array/cast_byte_array_int2.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
I'd merge `cast_byte_array_int.bal` and `cast_byte_array_int2.bal` together and cover both tests in the one .bal

2021-05-20 09:45 UTC, ruvi-d commented on test/array/cast_byte_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Ditto about adding skipped test

2021-05-20 09:45 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    let array: Box<DynamicBalArray<i64>> = Box::new(DynamicBalArray::<i64>::new(size, 3));
Avoid magic numbers, better use something like a enum for the header value

2021-05-20 09:45 UTC, ruvi-d commented on runtime/rust_rt/src/lib.rs
> +    if ref_ptr < 0 {
ref_ptr needs to be of type `u8 and then we can skip this `< 0`  check

2021-05-20 09:45 UTC, ruvi-d commented on runtime/c_rt/include/gc.h
> +void *alloc_array(size_t n_members, size_t member_size) {
Same as `zalloc`. Rename `zalloc` as `alloc_array`

2021-05-20 09:45 UTC, ruvi-d commented on runtime/c_rt/include/balarray.h
> +    uint64_t header;
no BalValue elements?

2021-05-20 09:45 UTC, ruvi-d commented on runtime/c_rt/include/balarray.h
> +    uint64_t header;
Seems that the header for DynamicArray is not required and you can keep the elements pointer in DynamicBalArray itself. Ref: https://github.com/jclark/nballerina-rt/blob/main/balrt.c#L164

2021-05-20 09:45 UTC, ruvi-d commented on runtime/c_rt/src/balarray.c
> +    if (header_type == 0) {
header values need to go to an enum

2021-05-20 09:45 UTC, ruvi-d commented on runtime/c_rt/include/balarray.h
> +int64_t castPointerToValue(DynamicBalArray *array_ptr, void *ptr);
these two can be static functions in .c. No need to make them external by defining it here.

2021-05-20 09:45 UTC, ruvi-d commented on compiler/reader/ConstantPool.cpp
> +    assert(value >= 0 && value <= 255);
use the limits macro instead of `0` and `255`: https://en.cppreference.com/w/cpp/types/integer

2021-05-20 09:45 UTC, ruvi-d commented on compiler/bir/Types.cpp
> +bool Type::checkArrayCastSupport(TypeTag destination, TypeTag source) {
args should be named `srcMemberType` and `destMemberType`

2021-05-20 10:03 UTC, heshanpadmasiri commented on test/array/cast_int_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
I added these test so when #323 is resolved these too should work

2021-05-20 10:03 UTC, heshanpadmasiri commented on test/array/cast_byte_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
I added these test so when #323 is resolved these too should work

2021-05-20 10:06 UTC, ruvi-d commented on test/array/cast_int_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
isn't this within the scope of this PR? pls correct me if otherwise

2021-05-20 10:29 UTC, heshanpadmasiri commented on runtime/c_rt/include/balarray.h
> +    uint64_t header;
Size and alignment of the elements are not known at the c side when compiling. (If it's a int array it's 64bit if a byte array it's 8 bits) We do the memory allocation at the rust side and I use the `getItemAt` function which consider both address of header and content of the header (which tells what is the internal data type) to calculate offsets due to this reason.

2021-05-20 11:04 UTC, heshanpadmasiri commented on runtime/c_rt/include/balarray.h
> +    uint64_t header;
I am using these structs to match the rust side (where we do the actual memory allocation still). So if I drop it here it will cause some changes in the rust side (basically internals of almost all the rust functions will change slightly) so is it okay to do that in this PR given that those changes are not strictly speaking related to array access.

2021-05-20 11:18 UTC, heshanpadmasiri commented on test/array/cast_byte_array_int2.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
`cast_byte_array_int.bal` actually testing the array cast instruction working (which currently does a static check to see if types can be casted) for byte to int while `cast_byte_array_int2.bal` don't get a cast instruction so it test whether the array access based purely on the header information is working correctly. So depending on which one fails we can easily figure out if the casting is to blame or not

2021-05-20 14:57 UTC, heshanpadmasiri commented on test/array/cast_int_array_any.bal.skip
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
This particular test shouldn't had been skipped it was my bad. The reason for skipping other tests are

1. If the underlying array type is `byte[]` we currently don't have a method to convert byte to any and any to byte
2. If there is a cast of the type `any a = i` not `any[] a = i`  where i is an array because it the case of the former we don't have a method to convert arrays to any. (This is latter where we have an array of any and this is handled)

In these cases I think solving them is out of the scope of this PR

2021-05-20 14:57 UTC, heshanpadmasiri commented on runtime/rust_rt/src/lib.rs
> +    let array: Box<DynamicBalArray<i64>> = Box::new(DynamicBalArray::<i64>::new(size, 3));
Fixed

2021-05-20 14:58 UTC, heshanpadmasiri commented on runtime/rust_rt/src/lib.rs
> +    if ref_ptr < 0 {
Fixed

2021-05-20 15:03 UTC, heshanpadmasiri commented on runtime/c_rt/src/balarray.c
> +    if (header_type == 0) {
Header type check updated to use enums for the case of bytes (ints are the default case). I couldn't find what are our data types that actually uses 16 and 32 bits so I didn't put enums for them. (We are using `uint64_t header_type = header & 3;` to extract just the last 2 bits because that is the part of the header that tells us the type.)

2021-05-20 15:04 UTC, heshanpadmasiri commented on runtime/c_rt/include/balarray.h
> +int64_t castPointerToValue(DynamicBalArray *array_ptr, void *ptr);
Fixed

2021-05-20 15:38 UTC, heshanpadmasiri commented on runtime/c_rt/include/gc.h
> +void *alloc_array(size_t n_members, size_t member_size) {
This part was removed since it is no longer used

2021-05-21 08:03 UTC, ruvi-d commented on runtime/c_rt/include/balarray.h
> +    uint64_t header;
ok

2021-11-05 03:15 UTC, manuranga commented
Closeing since project is moving to attic

2021-11-05 03:15 UTC, closed without merging