Migrate boolean to any cast to BalValue representation
ballerina-platform/nballerina-cpp pull request #316
Opened 2021-05-19 12:05 UTC by ushirask

## Purpose
Handle boolean to any conversion and vice versa with i8 ptr.
Resolves #269 

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-05-20 09:59 UTC, ruvi-d requested changes

2021-05-20 09:59 UTC, ruvi-d commented on test/any/cast_any_boolean_false.bal
> +// RUN: "%testRunScript" %s %nballerinacc "%java_path" "%target_variant" "%skip_bir_gen" | filecheck %s
Please join `cast_any_boolean_true.bal ` and `cast_any_boolean_false.bal` into one .bal

2021-05-20 09:59 UTC, ruvi-d commented on compiler/codegen/CodeGenUtils.cpp
> +        std::vector<llvm::Type *> arg_types = {llvm::Type::getInt8PtrTy(module.getContext())};
Use the `builder` APIs to more easily get Int8PtrTy

2021-05-20 14:41 UTC, ruvi-d requested changes

2021-05-20 14:41 UTC, ruvi-d commented on test/any/cast_any_boolean.bal
> +// CHECK: RESULT=false
Who about?
```
print_string("RESULT="); 
print_boolean(a11);
print_string("RESULT="); 
print_boolean(b11);
```

2021-05-21 07:59 UTC, ruvi-d approved these changes

2021-05-24 04:36 UTC, manuranga approved these changes

2021-05-24 04:36 UTC, merged